blank_issues_enabled: false
contact_links:
  - name: Suggest a feature or enhancement
    url: https://github.com/Everything-Compatible/YRDict/discussions/new?category=ideas-and-feedback
    about: If you want to suggest your idea to the project and/or upvote some ideas.
