name: Pull Request Nightly Build

on:
  pull_request:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  # GIT_COMMIT: $(git rev-parse --short "$GITHUB_SHA")
  # GIT_BRANCH: ${GITHUB_REF#refs/heads/}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
        # ref: ${{ github.event.pull_request.head.sha }}

    - name: Build YRDict
      uses: ./.github/actions/build-yrdict  # Setup steps are reused
      with:
        sln-path: ${{env.SOLUTION_FILE_PATH}}
        build-config: ${{env.BUILD_CONFIGURATION}}
